project               = "iot-minero-api-prod"
region                = "southamerica-west1"
zone                  = "southamerica-west1-a"
instance_name         = "iot-vm-dev"
machine_type          = "e2-micro"
ssh_user              = "julio"
ssh_pub_key_path      = "~/.ssh/id_rsa.pub"
service_account_email = "github-deployer@iot-minero-api-prod.iam.gserviceaccount.com"
