name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy API to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build API with Maven
        run: mvn -f api/pom.xml clean package -DskipTests

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/iot-api ./api

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker

      - name: Push Docker image to GCR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/iot-api

      - name: SSH into GCP VM and deploy containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            docker stop iot-api || true && docker rm iot-api || true
            docker stop postgres_iot || true && docker rm postgres_iot || true
            
            docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/iot-api
            
            docker network create iot-net || true
            
            docker run -d --name postgres_iot --network iot-net \
              -e POSTGRES_DB=db_iot \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=1234 \
              -p 5432:5432 postgres:15
            
            docker run -d --name iot-api --network iot-net \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_iot:5432/db_iot \
              -e SPRING_DATASOURCE_USERNAME=postgres \
              -e SPRING_DATASOURCE_PASSWORD=1234 \
              -p 8080:8080 gcr.io/${{ secrets.GCP_PROJECT_ID }}/iot-api
