name: Deploy to GCP - PROD

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    name: Build & Deploy API to GCP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests (solo módulo API)
        run: mvn -pl api -am test

      - name: Build API with Maven
        run: mvn -pl api -am clean package -DskipTests

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/iot-api:prod ./api

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Docker Push
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/iot-api:prod

      - name: SSH into GCP VM and deploy containers PROD
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP_PROD }}
          username: ${{ secrets.GCP_VM_USER_PROD }}
          key: ${{ secrets.GCP_VM_SSH_KEY_PROD }}
          script: |
            cd ~/api-iot
            git pull origin master
            docker compose -f docker-compose.deploy.yml down
            docker compose -f docker-compose.deploy.yml build
            docker compose -f docker-compose.deploy.yml up -d
