name: Terraform Plan Validator

on:
  pull_request:
    paths:
      - 'infra/**.tf'

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Auth to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Init Terraform (${{
          matrix.environment }})
        run: terraform -chdir=infra/${{ matrix.environment }} init

      - name: Validate Terraform
        run: terraform -chdir=infra/${{ matrix.environment }} validate

      - name: Run Terraform Plan
        run: terraform -chdir=infra/${{ matrix.environment }} plan
        env:
          GOOGLE_CREDENTIALS: '${{ secrets.GCP_SA_KEY }}'
